Ingredient.create(name: 'Link sausage')
Ingredient.create(name: 'Lorne sausage')
Ingredient.create(name: 'Bacon')
Ingredient.create(name: 'Fried egg')
Ingredient.create(name: 'Scrambled egg')
Ingredient.create(name: 'Tattie scone')
Ingredient.create(name: 'Tomato ketchup')
Ingredient.create(name: 'Brown sauce')
